version: '2.1'

services:
  chainpoint-ntpd:
    build: .
    image: chainpoint-ntpd:latest
    container_name: chainpoint-ntpd
    hostname: ntpd
    restart: on-failure:2
    cap_add:
      - SYS_TIME
      - SYS_NICE
    mem_limit: 64M
